[package]
name = "roloc"
version = "0.3.1"
edition = "2021"

[dependencies]
clap = "4.1"
image = "0.25"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rand = "0.9"

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "kmeans_bench"
harness = false
